import Cookies from "js-cookie";
import { useRouter } from "next/router";
import { useSnackbar } from "notistack";
import { useMutation } from "react-query";
import { KEY_STORAGE } from "src/constants/common";
import { routerURL } from "src/navigation/router";
import { checkSuccessRequest, getToken } from "src/service/api";
import loginServices from "src/service/login";

export const useLogin = () => {
  const router = useRouter();
  const { enqueueSnackbar } = useSnackbar();
  const handleLogin = useMutation(
    async (params: any) => {

      try {
        const response = await loginServices.handleLogin(params);

        return { response }
      } catch (error) {
        throw error;
      }
    },
    {
      onSuccess: (res: any) => {

        if (checkSuccessRequest(res?.response?.data)) {

          const token = res?.response?.data?.data?.session?.accessToken;
          const refreshToken = res?.response?.data?.data?.session?.refreshToken;

console.log(token);
const mama = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTRiNDRlYWNiMzA0N2E0OGNlZGI4M2UiLCJkZWxldGVkX2F0IjpudWxsLCJlbWFpbCI6ImNvbXBhbnlAdnNhbS52biIsInVzZXJfbmFtZSI6ImFkbWluIiwicm9sZSI6InN1cGVyX2FkbWluIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwaG9uZV92ZXJpZmllZCI6ZmFsc2UsImRldmljZV9zZXNzaW9ucyI6WyI2NTRiNDUyYmNiMzA0N2E0OGNlZGI4NDciLCI2NTRiNDcyOTJlYzJiZmFlYzJhNzAzMjIiLCI2NTRiNDc2MGNiMzA0N2E0OGNlZGI4NjgiLCI2NTRiNTFlOTQzNzY5MTU0MWI5YzgyZGMiLCI2NTRiOTRlMGNiZWE5MDViMWNkNTdmNDUiLCI2NTRiOTUzM2NiZWE5MDViMWNkNTdmNjciLCI2NTU0NGMyYjJmNmQxODY1N2Q2NDI5OWMiLCI2NTU0NGMzZjJmNmQxODY1N2Q2NDI5YTUiLCI2NTU0NGRiNDJmNmQxODY1N2Q2NDI5YjUiLCI2NTU0NGVkMzJmNmQxODY1N2Q2NDI5YzciLCI2NTU0NGVlODJmNmQxODY1N2Q2NDI5ZDIiLCI2NTU0NGYxNjJmNmQxODY1N2Q2NDI5ZGQiLCI2NTU0NGYzYjJmNmQxODY1N2Q2NDI5ZTgiLCI2NTU0NGZiMzJmNmQxODY1N2Q2NDI5ZjIiLCI2NTU0NTBhODJmNmQxODY1N2Q2NDJhNGQiLCI2NTU0NTFiMTJmNmQxODY1N2Q2NDJhNjUiLCI2NTViMTJlNzJmOTg1YmIwNDE1ZWY0MzkiLCI2NTViMTMwYjJmOTg1YmIwNDE1ZWY0NDMiLCI2NTViMTM3YjJmOTg1YmIwNDE1ZWY0NGQiLCI2NTViMTM5YzJmOTg1YmIwNDE1ZWY0NTciLCI2NTViMTNiMjJmOTg1YmIwNDE1ZWY0NjEiLCI2NTViMTNiODJmOTg1YmIwNDE1ZWY0NjkiLCI2NTViMTQyMjJmOTg1YmIwNDE1ZWY0NzMiLCI2NTViMTk5ZDJmOTg1YmIwNDE1ZWY0N2MiLCI2NTViMTlmZDJmOTg1YmIwNDE1ZWY0ODUiLCI2NTViMWExZTJmOTg1YmIwNDE1ZWY0OGUiLCI2NTViMWEzNzJmOTg1YmIwNDE1ZWY0OTciLCI2NTViMWFhYTJmOTg1YmIwNDE1ZWY0YTAiLCI2NTViMWFiNDJmOTg1YmIwNDE1ZWY0YTkiLCI2NTViMWJiNjJmOTg1YmIwNDE1ZWY0YjIiLCI2NTViMWJjZTJmOTg1YmIwNDE1ZWY0YmIiLCI2NTViMWJkZTJmOTg1YmIwNDE1ZWY0YzQiLCI2NTViMWJmMjJmOTg1YmIwNDE1ZWY0Y2QiLCI2NTViMWNhNTJmOTg1YmIwNDE1ZWY0ZDkiLCI2NTViMWNjYTJmOTg1YmIwNDE1ZWY0ZTIiLCI2NTViMWQwNjJmOTg1YmIwNDE1ZWY0ZWIiLCI2NTViMWQxMDJmOTg1YmIwNDE1ZWY0ZjciLCI2NTViMWRkNjJmOTg1YmIwNDE1ZWY1MDMiLCI2NTViMWRkYzJmOTg1YmIwNDE1ZWY1MGMiLCI2NTViMWRlYTJmOTg1YmIwNDE1ZWY1MTgiLCI2NTViMWU3MjJmOTg1YmIwNDE1ZWY1MjUiLCI2NTViMWVjMjJmOTg1YmIwNDE1ZWY1MzEiLCI2NTViMWYwNzJmOTg1YmIwNDE1ZWY1M2UiLCI2NTViMWYxMTJmOTg1YmIwNDE1ZWY1NDgiLCI2NTViMmU1MGMwODJmNzkxOTE0YjUyYTEiLCI2NTViMmVmMWMwODJmNzkxOTE0YjUyYWEiLCI2NTViMmZhMmMwODJmNzkxOTE0YjUyYjciLCI2NTViMmZiMWMwODJmNzkxOTE0YjUyYzAiLCI2NTViMmZkYmMwODJmNzkxOTE0YjUyYzkiLCI2NTViMmZmMmMwODJmNzkxOTE0YjUyZDEiLCI2NTViMzA0OGMwODJmNzkxOTE0YjUyZGMiLCI2NTViMzA1N2MwODJmNzkxOTE0YjUyZTciLCI2NTViMzExYWMwODJmNzkxOTE0YjUzMDMiLCI2NTViMzEzMGMwODJmNzkxOTE0YjUzMGUiLCI2NTViMzE0M2MwODJmNzkxOTE0YjUzMTUiLCI2NTViMzE0YmMwODJmNzkxOTE0YjUzMjAiLCI2NTViMzFiZmMwODJmNzkxOTE0YjUzMmIiLCI2NTViMzFkYWMwODJmNzkxOTE0YjUzMzYiLCI2NTViMzFmZGMwODJmNzkxOTE0YjUzNDEiLCI2NTViMzIxZGMwODJmNzkxOTE0YjUzNGMiLCI2NTViMzI2ZWMwODJmNzkxOTE0YjUzNTciLCI2NTViMzJiOWMwODJmNzkxOTE0YjUzNjIiLCI2NTViMzJkMmMwODJmNzkxOTE0YjUzNmQiLCI2NTViMzNhNGMwODJmNzkxOTE0YjUzNzgiLCI2NTViMzNiOGMwODJmNzkxOTE0YjUzODMiLCI2NTViMzNjOWMwODJmNzkxOTE0YjUzOGUiLCI2NTViMzNlMmMwODJmNzkxOTE0YjUzOTkiLCI2NTViMzQ4NGMwODJmNzkxOTE0YjUzYTQiLCI2NTViMzQ5NWMwODJmNzkxOTE0YjUzYWYiLCI2NTViMzU0OWMwODJmNzkxOTE0YjUzYmEiLCI2NTViMzU1ZWMwODJmNzkxOTE0YjUzYzUiLCI2NTViMzViMWMwODJmNzkxOTE0YjUzZDAiLCI2NTViMzYwMmMwODJmNzkxOTE0YjUzZGIiLCI2NTViMzYzZmMwODJmNzkxOTE0YjUzZTYiLCI2NTViMzY1NWMwODJmNzkxOTE0YjUzZjEiLCI2NTViMzZiNmMwODJmNzkxOTE0YjUzZmMiLCI2NTViMzZlNWMwODJmNzkxOTE0YjU0MDciLCI2NTViMzZmNGMwODJmNzkxOTE0YjU0MTIiLCI2NTViMzcxOGMwODJmNzkxOTE0YjU0MWQiLCI2NTViMzcyN2MwODJmNzkxOTE0YjU0MjgiLCI2NTViNWJkYzlhYWMzNTEzZTlmOTRhZDIiLCI2NTViNWJmMjlhYWMzNTEzZTlmOTRhZGQiLCI2NTViNjUyNDZjOTFiMGZjYmVlOWNmZmIiLCI2NTViNjU0YzZjOTFiMGZjYmVlOWQwMDMiLCI2NTViNjkwNTZjOTFiMGZjYmVlOWQwMGUiLCI2NTVjMWJmNzEwZTUyZDhiNDAyMjkwMzQiLCI2NTVjMWMwNjEwZTUyZDhiNDAyMjkwM2MiLCI2NTVjMWMwODEwZTUyZDhiNDAyMjkwNDMiLCI2NTVjMWMwZjEwZTUyZDhiNDAyMjkwNGIiLCI2NTVjMWMxOTEwZTUyZDhiNDAyMjkwNTMiLCI2NTVjMWMyZDEwZTUyZDhiNDAyMjkwNWIiLCI2NTVjMWMzMTEwZTUyZDhiNDAyMjkwNjIiLCI2NTVjMWM3ZDEwZTUyZDhiNDAyMjkwNmQiLCI2NTVjMWM4MjEwZTUyZDhiNDAyMjkwNzUiLCI2NTVjMWUyNTEwZTUyZDhiNDAyMjkwN2QiLCI2NTVjMWU1NTEwZTUyZDhiNDAyMjkwODUiLCI2NTVjMWY0NTEwZTUyZDhiNDAyMjkwOWQiLCI2NTVjMWY1YzEwZTUyZDhiNDAyMjkwYTUiLCI2NTVjMWY3OTEwZTUyZDhiNDAyMjkwYjAiLCI2NTVjMWY5OTEwZTUyZDhiNDAyMjkwYmIiLCI2NTVjMWZhNjEwZTUyZDhiNDAyMjkwYzIiLCI2NTVjMWZiNTEwZTUyZDhiNDAyMjkwYzkiLCI2NTVjMWZjNTEwZTUyZDhiNDAyMjkwZDAiLCI2NTVjMWZkMDEwZTUyZDhiNDAyMjkwZGMiLCI2NTVjMWZmMjFiYWNmZTFmNzQxNjliMTgiLCI2NTVjMjAwMjFiYWNmZTFmNzQxNjliMWYiLCI2NTVjMjA0ODFiYWNmZTFmNzQxNjliMjYiLCI2NTVjMjA2NDFiYWNmZTFmNzQxNjliMmQiLCI2NTVjMjBhMTFiYWNmZTFmNzQxNjliMzQiLCI2NTVjMjBkNDkwOTg1ZDA1ODA4YTU1NWQiLCI2NTVjMjBlYzkwOTg1ZDA1ODA4YTU1NjQiLCI2NTVjMjE2MzkwOTg1ZDA1ODA4YTU1NmIiLCI2NTVjMjE4MDkwOTg1ZDA1ODA4YTU1NzIiLCI2NTVjMjFhMDkwOTg1ZDA1ODA4YTU1N2EiLCI2NTVjMjFhMTkwOTg1ZDA1ODA4YTU1ODAiLCI2NTVjMjFkYTkwOTg1ZDA1ODA4YTU1ODciLCI2NTVjMjFlMzkwOTg1ZDA1ODA4YTU1OGUiLCI2NTVjMjFlYzkwOTg1ZDA1ODA4YTU1OTUiLCI2NTVjMjIzODkwOTg1ZDA1ODA4YTU1OWMiLCI2NTVjMjI1ZDkwOTg1ZDA1ODA4YTU1YTMiLCI2NTVjMjM0MzkwOTg1ZDA1ODA4YTU1YWEiLCI2NTVjMjM1MDkwOTg1ZDA1ODA4YTU1YjEiLCI2NTVjMjRjODkwOTg1ZDA1ODA4YTU1YjgiLCI2NTVjMjUyZTkwOTg1ZDA1ODA4YTU1YmYiLCI2NTVjMjU3YTkwOTg1ZDA1ODA4YTU1YzYiLCI2NTVjMjViMjkwOTg1ZDA1ODA4YTU1Y2QiLCI2NTVjMjYwMTEyMDYxN2I1NjY3ZDczZWMiLCI2NTVjMjYxZTkwOTg1ZDA1ODA4YTU1ZDQiLCI2NTVjMjYyMDkwOTg1ZDA1ODA4YTU1ZGIiLCI2NTVjMjYzODEyMDYxN2I1NjY3ZDczZjMiLCI2NTVjMjY5MjEyMDYxN2I1NjY3ZDczZmEiLCI2NTVjMjZkOTEyMDYxN2I1NjY3ZDc0MDEiLCI2NTVjMjc1MjEyMDYxN2I1NjY3ZDc0MDgiLCI2NTVjMjdlYTEyMDYxN2I1NjY3ZDc0MGYiLCI2NTVjMjg2ZDEyMDYxN2I1NjY3ZDc0MTYiLCI2NTVjMjhlODEyMDYxN2I1NjY3ZDc0MWQiLCI2NTVjMjkwYTEyMDYxN2I1NjY3ZDc0MjQiLCI2NTVjMjkyZDEyMDYxN2I1NjY3ZDc0MmIiLCI2NTVjMjk5MjkwOTg1ZDA1ODA4YTU1ZTIiLCI2NTVjMjlhZTEyMDYxN2I1NjY3ZDc0MzIiLCI2NTVjMmE3YzEyMDYxN2I1NjY3ZDc0MzkiLCI2NTVjMmFhMTEyMDYxN2I1NjY3ZDc0NDAiLCI2NTVjMmI2NzEyMDYxN2I1NjY3ZDc0NDciLCI2NTVjMmJiODkwOTg1ZDA1ODA4YTU1ZTkiLCI2NTVjMmJjZTEyMDYxN2I1NjY3ZDc0NGUiLCI2NTVjMmMwZjkwOTg1ZDA1ODA4YTU1ZjAiLCI2NTVjMmM3YzkwOTg1ZDA1ODA4YTU1ZjciLCI2NTVjMmM4OTkwOTg1ZDA1ODA4YTU1ZmUiLCI2NTVjMmNkZDEyMDYxN2I1NjY3ZDc0NTUiLCI2NTVjMmQ1NjEyMDYxN2I1NjY3ZDc0NWMiLCI2NTVjMmRmNTEyMDYxN2I1NjY3ZDc0NjQiLCI2NTVjMmVmOTkwOTg1ZDA1ODA4YTU2MDUiLCI2NTVjMmY1ZjEyMDYxN2I1NjY3ZDc0NmIiLCI2NTVjMmY2NjkwOTg1ZDA1ODA4YTU2MGMiLCI2NTVjMmZkODkwOTg1ZDA1ODA4YTU2MTMiLCI2NTVjMzAwMDEyMDYxN2I1NjY3ZDc0NzIiLCI2NTVjMzAxNTkwOTg1ZDA1ODA4YTU2MWEiLCI2NTVjMzAzZjkwOTg1ZDA1ODA4YTU2MjEiLCI2NTVjMzA1NTkwOTg1ZDA1ODA4YTU2MjgiLCI2NTVjMzBiNDEyMDYxN2I1NjY3ZDc0NzkiLCI2NTVjMzBiYTkwOTg1ZDA1ODA4YTU2MmYiLCI2NTVjMzBlMzkwOTg1ZDA1ODA4YTU2MzYiLCI2NTVjMzBmNjkwOTg1ZDA1ODA4YTU2M2QiLCI2NTVjMzExMzkwOTg1ZDA1ODA4YTU2NDQiLCI2NTVjMzEyMzkwOTg1ZDA1ODA4YTU2NGIiLCI2NTVjMzEzMzEyMDYxN2I1NjY3ZDc0ODAiLCI2NTVjMzE1YzkwOTg1ZDA1ODA4YTU2NTIiLCI2NTVjMzFkYTkwOTg1ZDA1ODA4YTU2NTkiLCI2NTVjMzFmNjkwOTg1ZDA1ODA4YTU2NjAiLCI2NTVjMzJhMjEyMDYxN2I1NjY3ZDc0ODciLCI2NTVjMzJiZTkwOTg1ZDA1ODA4YTU2NjciLCI2NTVjMzJjYzEyMDYxN2I1NjY3ZDc0OGUiLCI2NTVjMzMwZjkwOTg1ZDA1ODA4YTU2NmUiLCI2NTVjMzM4YzkwOTg1ZDA1ODA4YTU2NzUiLCI2NTVjMzQxMTEyMDYxN2I1NjY3ZDc0OTUiLCI2NTVjMzQ1NzEyMDYxN2I1NjY3ZDc0OWMiLCI2NTVjMzQ4ODEyMDYxN2I1NjY3ZDc0YTMiLCI2NTVjMzRkNjEyMDYxN2I1NjY3ZDc0YWEiLCI2NTVjMzU0YjEyMDYxN2I1NjY3ZDc0YjEiXSwiY3JlYXRlZF9hdCI6IjIwMjMtMTEtMDhUMDg6MjA6NTguNzUwWiIsInVwZGF0ZWRfYXQiOiIyMDIzLTExLTIxVDA0OjQyOjUyLjIyMloiLCJfX3YiOjMsImlhdCI6MTcwMDU0MTg0NSwiZXhwIjoxNzAwNTQzNjQ1fQ.qVFY_DcEJi0ORg4QjLPG05rOhsgf1TLE4qREtPtevds'
const blob = new Blob([mama]);
console.log(blob.size/1024);

          Cookies.set('access-token', token);
          Cookies.set(KEY_STORAGE.REFRESH_TOKEN, refreshToken);
          getToken(token);
         
          enqueueSnackbar("Login Successfully!", {
            variant: 'success',
            autoHideDuration: 2000,
          });
          router.push("/");
        }
        else {
          enqueueSnackbar("User Name or Pass Word Invalid!", {
            variant: 'error',
            autoHideDuration: 2000,
          });
        }
      },
    },
  );

  return {
    onLogin: handleLogin.mutate,
  };
};

export const useLogout = () => {
  const router = useRouter();
  const { enqueueSnackbar } = useSnackbar();
  const handleLogout = useMutation(
    async () => {
      try {
        const response = await loginServices.handleLogout();

        return { response }
      } catch (error) {
        throw error;
      }
    },
    {
      onSuccess: (res: any) => {

        if (checkSuccessRequest(res?.response?.data)) {

          Cookies.remove(KEY_STORAGE.TOKEN)
          Cookies.remove(KEY_STORAGE.REFRESH_TOKEN)
          enqueueSnackbar("Logout Successfully!", {
            variant: 'success',
            autoHideDuration: 2000,
          });
          router.push(routerURL.LOGIN);
        }
        else {
          // ShowMessage(TYPE_CONSTANTS.MESSAGE.ERROR, "Login fail !");
        }
      },
    },
  );

  return {
    onLogout: handleLogout.mutate,
  };
};